# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
# XWayland settings
xwayland {
    force_zero_scaling = true
}
